appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appImageTag: v0.3.4
appReplicaCount: 2
containerPort: 7070
servicePort: 7070
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "7070"
  - name: REDIS_ADDR
    value: "redis-cart:6379"
