appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appImageTag: v0.3.4
appReplicaCount: 2
containerPort: 8080
servicePort: 5000
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "8080"
