appName: frontend
appImage: gcr.io/google-samples/microservices-demo/frontend
appImageTag: v0.3.4
appReplicaCount: 2
containerPort: 8080
servicePort: 80
serviceType: LoadBalancer
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:8080"
  - name: RECOMMENDATION_SERVICE_ADDR
    value: "recommendationservice:8080"
  - name: CHECKOUT_SERVICE_ADDR
    value: "checkoutservice:5050"
  - name: AD_SERVICE_ADDR
    value: "adservice:9555"
