
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1USXlNekU1TlRnME9Wb1hEVE14TVRJeU1URTVOVGcwT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHBJCmlwaDMzVXpyMGVwUlNkV1JuN05aVlIrTjE5aC9acEE5OWFyd3BKWTJzRytLSXZPdXk4c0VTbmhPeWJ4TDdTdWkKcEQ1bXloNFZCU24vYzJNamFBSExWVjdRcHhxSWQ4bEZaWkRhaGRhSXFoQ0NkZ1F3V1BTb3hnQ2I2Mzdqc0dGVAplMForeTJDMjBNWjhFLzA5N1cyVzV3R3RLU0hLYkJPOTZrSzFkVHk4Q1hsRmZzR2hmMlpkM1JhTFZ3ZlVickt3CjZWbndPb20rWVUrazRlbFNjai82UFVzamM0WFJQcmJKOHdONFF6cTI4dnVUc3diWU4veENMOS9DaEZ1SEJ5VzcKbWpIQTdQTHZubnZuZmRPT1JyL1duU3cyRlREU0hneE5pREF1enFnNm9Wb0hDMUVaUFRhN0NHNlVMNDVQenF3WgpaRGtwWHRobmRTS3QwVHE3clRFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNWVAyVVdhSklOK3RYdmF1WSs5ZjI4TjZtZW1NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSjh5cW5jOVVWN21NSTQvZDZLSApRQjVaU1VkcVBjUHU0VExHVmV4VmRFQjlnZ2hENjBEUFJXMEphVFBDVnMrM1dTelByUFN1YkU1cUNVdStueGVhCkxDUC9lOGZ3dzUrNmdDSmpaZXoxRmthSk1tandYRlEyVE5abmY5b3FreWFRcDNqc01ZajhuTUpLQkROd2V3UEoKUVYyNU9KZEYxUHByd2V3SWlzWUZjSUNMSEJJUlNJZkpQSXd1WEYvZ0FOcEFML0pyTGlCcVZ6Y3dGa0VvSVFaRwpGWjZWcmw4eEJBRlNBQUswMEJJQmtycGhNSW94S3dWTlBnTTFCNmUvbkd6MWo2MGtmZ0ZrNmFGQXhIL213M3JpClZIUDA0bFdMYkVDeUJkdkptTnloVGVXZWJOUFhHZzVpc29Zd1RKSTlyMXl3VkRXZ3NrdHg0aXgvZmFsNWZRak8KTTVvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://84306fbd-d19d-42d2-9126-4c038d4a6bf2.us-east-2.linodelke.net:443
  name: lke47336

users:
- name: lke47336-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjY0Q0g4X0FHbjdEeUxUb193dzd4eUVaOHRwUWVlN3JKaUJYTXFuZWF0MGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcWZ2MnYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMmM4NDUxM2QtMGE4NC00NmQ2LTg2MGMtOTAwNjA3MjMwYTdjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Pn7J5CUu-0b8sFOnQ-3EB_rqKPkmx8MsgAq6tnx6XWDVeNbas3BCrlaXEeSAnLfkFb5GUlGqZ7iC5se6Q9USKntulKg8L4KfbhRhvV3gaA2Cv89GQmhV0St6isNFUcOX5NxusASij3JTyiSRzXTjSwU8AzBliaBnCdPipXkGbKHDZf34wKqysIGZJ6lgk3bxL1LraJbVgJLEg8KASogBnmNPJyGVESpnIYZ7lHU13i6oZSjJx37ZNAzuRdvLTO7c7ZuHZ0-oC1kg4lbV1vkMeqfY8xVaptyBJ6970RJPEjXZiQgahh4HI1GF0EWbArCK0EJkeT6YCh5nSPMBVP6QSA

contexts:
- context:
    cluster: lke47336
    namespace: default
    user: lke47336-admin
  name: lke47336-ctx

current-context: lke47336-ctx
