apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority-data: XXXXXX
      server: https://84306fbd-d19d-42d2-9126-4c038d4a6bf2.us-east-2.linodelke.net:443
    name: lke47336

users:
  - name: lke47336-admin
    user:
      as-user-extra: {}
      token: XXXXXXXX

contexts:
  - context:
      cluster: lke47336
      namespace: default
      user: lke47336-admin
    name: lke47336-ctx

current-context: lke47336-ctx
