apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName}}"
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: "{{ .Values.appName}}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName}}"
    spec:
      containers:
        - name: "{{ .Values.appName}}"
          image: "{{ .Values.appImage }}:{{ .Values.appImageTag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: "{{ .Values.volumeName}}"
              mountPath: "{{ .Values.mountPath}}"
      volumes:
        - name: "{{ .Values.volumeName}}"
          emptyDir: {}
